apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  persistentVolumeReclaimPolicy: Retain
