apiVersion: v1
kind: Service
metadata:
  name: redmine
  namespace:  {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: redmine
