# Common Labels
labels:
  app: "egov-pb-digilocker"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "digilocker"



# Container Configs
image:
  repository: "egov-pb-digilocker"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"    
